name: WF-CD-development

on:
  push:
    branches:
      - develop

jobs:
  build-develop-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build website
        run: |
          npx parcel build "index.html" --dist-dir "./dev" --public-url "./"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dev"

  deploy-develop-job:
    needs: build-develop-job
    environment: "deployment-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
